server:
  port: 8085

security:
  enabled: false

dgs:
  graphql:
    schema-locations:
      - classpath*:schema/**/*.graphql*
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG