package dreipc.asset.search.commands;

public enum Operation {
    CREATE_TAGS,
    UPDATE_TAGS,
    CREATE_TOPICS,
    UPDATE_TOPICS,
    CREATE_ASSET_INDEX,
    DELETE_ASSET_INDEX,
    CREATE_PAGE_INDEX,
    DELETE_PAGE_INDEX,
    DELETE_MUSEUM_OBJECT_INDEX, CREATE_MUSEUM_OBJECT_INDEX
}
